### ISSUE TITLE
Test https-over-https-error.js fails on nodejs v0.12.7

### ISSUE THREAD

**Issue by mar4uk** [koichik/node-tunnel#16]
1) HTTPS over HTTPS authentication failed should finish without error:

```
  Uncaught AssertionError: expected 2 to be 1
  + expected - actual

  -2
  +1

  at Assertion.fail (node_modules/should/lib/assertion.js:91:17)
  at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:163:19)
  at Server.<anonymous> (test/https-over-https-error.js:253:28)
  at net.js:1419:10
```

**Comment by koichik** [comment]
Yeah, this is the reason why I couldn't release `tunnel@v0.0.4` in a long time.
However, the test is passing with iojs v1.4.1 or later including node v4 and v5.

**Comment by koichik** [comment]
Node v0.12 is outdated, closing.
